// User and Admin Enums
export enum Role {
  MASTER_ADMIN = "MASTER_ADMIN",
  SERVICE_ADMIN = "SERVICE_ADMIN",
  EMPLOYEE = "EMPLOYEE",
  USER = "USER"
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  BANNED = "BANNED",
  RESTRICTED = "RESTRICTED"
}

export enum UserTripStatus {
  PLANNING = "PLANNING",
  SAVED = "SAVED",
  BOOKED = "BOOKED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}

// Location and Tourism Enums
export enum LocationType {
  COUNTRY = "COUNTRY",
  STATE = "STATE",
  DIVISION = "DIVISION",
  DISTRICT = "DISTRICT",
  CITY = "CITY",
  METROPOLITON = "METROPOLITON",
  VILLAGE = "VILLAGE",
  AREA = "AREA",
  ISLAND = "ISLAND",
  COUNTRYSIDE = "COUNTRYSIDE"
}

export enum CategoryType {
    AMENITY = "AMENITY",
    POLICY = "POLICY",
    HOTEL_TYPE = "HOTEL_TYPE",
    FACILITY = "FACILITY",
    RULE = "RULE" 
}

export enum TourType {
  ADVENTURE = "ADVENTURE",
  CULTURAL = "CULTURAL",
  BEACH = "BEACH",
  CITY_TOUR = "CITY_TOUR",
  NATURE = "NATURE",
  RELIGIOUS = "RELIGIOUS",
  HISTORICAL = "HISTORICAL"
}

export enum ActivityType {
  SIGHTSEEING = "SIGHTSEEING",
  ADVENTURE_SPORTS = "ADVENTURE_SPORTS",
  WATER_ACTIVITIES = "WATER_ACTIVITIES",
  CULTURAL_EXPERIENCE = "CULTURAL_EXPERIENCE",
  FOOD_TASTING = "FOOD_TASTING",
  SHOPPING = "SHOPPING",
  WILDLIFE = "WILDLIFE"
}

// Hotel and Accommodation Enums
export enum HotelType {
  LUXURY = "LUXURY",
  BUDGET = "BUDGET",
  BOUTIQUE = "BOUTIQUE",
  RESORT = "RESORT",
  HOSTEL = "HOSTEL",
  GUESTHOUSE = "GUESTHOUSE",
  APARTMENT = "APARTMENT"
}

export enum HotelServiceType {
  MEDIUM_RANGE = "MEDIUM_RANGE",
  LUXURY = "LUXURY",
  BUDGET = "BUDGET",
  SELF_MANAGED = "SELF_MANAGED"
}

// Transport Enums
export enum TransportServiceType {
  BUS = "BUS",
  FLIGHT = "FLIGHT",
  TRAIN = "TRAIN",
  CAR_RENTAL = "CAR_RENTAL",
  FERRY = "FERRY",
  SELF_MANAGED = "SELF_MANAGED"
}

export enum BusServiceType {
  AC_SLEEPER = "AC_SLEEPER",
  NON_AC_SLEEPER = "NON_AC_SLEEPER",
  AC_SEATER = "AC_SEATER",
  NON_AC_SEATER = "NON_AC_SEATER",
  DELUXE = "DELUXE",
  SEMI_DELUXE = "SEMI_DELUXE",
  LUXURY = "LUXURY"
}

export enum FlightServiceType {
  ECONOMY = "ECONOMY",
  BUSINESS = "BUSINESS",
  FIRST_CLASS = "FIRST_CLASS",
  PREMIUM_ECONOMY = "PREMIUM_ECONOMY"
}

export enum TrainServiceType {
  AC_1_TIER = "AC_1_TIER",
  AC_2_TIER = "AC_2_TIER",
  AC_3_TIER = "AC_3_TIER",
  SLEEPER = "SLEEPER",
  GENERAL = "GENERAL",
  CHAIR_CAR = "CHAIR_CAR"
}

// Payment and Transaction Enums
export enum PaymentStatus {
  UNPAID = "UNPAID",
  PAID = "PAID"
}

export enum RefundStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}

export enum WalletStatus {
  ACTIVE = "ACTIVE",
  LOCKED = "LOCKED",
  SUSPENDED = "SUSPENDED",
  CLOSED = "CLOSED"
}

export enum WalletTransactionType {
  CREDIT = "CREDIT",
  DEBIT = "DEBIT",
  TRANSFER_IN = "TRANSFER_IN",
  TRANSFER_OUT = "TRANSFER_OUT",
  CASHBACK = "CASHBACK",
  REFUND = "REFUND",
  PENALTY = "PENALTY",
  BONUS = "BONUS"
}

export enum TransactionStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  REVERSED = "REVERSED"
}

// Service and Booking Enums
export enum ServiceType {
  HOTEL_BOOKING = "HOTEL_BOOKING",
  TOUR_PACKAGE = "TOUR_PACKAGE",
  TRANSPORT_SERVICE = "TRANSPORT_SERVICE",
  ACTIVITY_BOOKING = "ACTIVITY_BOOKING",
  GUIDE_SERVICE = "GUIDE_SERVICE"
}

export enum BookingStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  REFUNDED = "REFUNDED",
  NO_SHOW = "NO_SHOW"
}

// Review and Rating Enums
export enum ReviewType {
  HOTEL = "HOTEL",
  TOUR_SPOT = "TOUR_SPOT",
  ACTIVITY_SPOT = "ACTIVITY_SPOT"
}

// System and Admin Enums
export enum Priority {
  NORMAL = "NORMAL",
  URGENT = "URGENT"
}

export enum SiteStatus {
  ACTIVE = "ACTIVE",
  DOWN = "DOWN"
}

export enum HeroSection {
  TOP = "TOP",
  MIDDLE = "MIDDLE",
  BOTTOM = "BOTTOM"
}

export enum AdminAction {
  CREATED_HOTEL = "CREATED_HOTEL",
  UPDATED_HOTEL = "UPDATED_HOTEL",
  DELETED_HOTEL = "DELETED_HOTEL",
  CREATED_TOURSPOT = "CREATED_TOURSPOT",
  UPDATED_TOURSPOT = "UPDATED_TOURSPOT",
  DELETED_TOURSPOT = "DELETED_TOURSPOT",
  CREATED_ACTIVITYSPOT = "CREATED_ACTIVITYSPOT",
  UPDATED_ACTIVITYSPOT = "UPDATED_ACTIVITYSPOT",
  DELETED_ACTIVITYSPOT = "DELETED_ACTIVITYSPOT",
  CREATED_LOCATION = "CREATED_LOCATION",
  UPDATED_LOCATION = "UPDATED_LOCATION",
  DELETED_LOCATION = "DELETED_LOCATION",
  CREATED_TOURPACKAGE = "CREATED_TOURPACKAGE",
  UPDATED_TOURPACKAGE = "UPDATED_TOURPACKAGE",
  DELETED_TOURPACKAGE = "DELETED_TOURPACKAGE",
  USER_MANAGEMENT = "USER_MANAGEMENT",
  PAYMENT_REFUND = "PAYMENT_REFUND",
  SITE_CONFIG = "SITE_CONFIG"
}

export enum EntityType {
  HOTEL = "HOTEL",
  TOUR_SPOT = "TOUR_SPOT",
  ACTIVITY_SPOT = "ACTIVITY_SPOT",
  LOCATION = "LOCATION",
  TOUR_PACKAGE = "TOUR_PACKAGE",
  USER = "USER",
  PAYMENT = "PAYMENT",
  SITE_CONFIG = "SITE_CONFIG"
}

export enum ComplaintStatus {
  PENDING = "PENDING",
  UNDER_REVIEW = "UNDER_REVIEW",
  UNSOLVED = "UNSOLVED",
  SOLVED = "SOLVED",
  CLOSED = "CLOSED"
}

